[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#d4af37"
backgroundColor = "#f0ede5"
secondaryBackgroundColor = "#e8e3db"
textColor = "#2c3e50"
font = "sans serif"

[global]
developmentMode = false
